# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-07 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40, verbose_name='State/Province/Region')),
                ('postal_code', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=40)),
                ('residency_in_indiana', models.CharField(max_length=40)),
                ('is_permanent_mailing_address', models.BooleanField(default=False)),
                ('permanent_address', models.TextField()),
                ('permanent_city', models.CharField(max_length=40)),
                ('permanent_state', models.CharField(max_length=150, verbose_name='State/Province/Region')),
                ('permanent_postal_code', models.CharField(max_length=5)),
                ('permanent_country', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EducatorRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InstituteAffilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IUEducationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualtrics_application_id', models.CharField(max_length=40)),
                ('qualtrics_completion_date', models.DateField()),
                ('requested_start_date', models.DateField()),
                ('required_teaching_experience', models.BooleanField(default=False)),
                ('highest_degree', models.CharField(max_length=100)),
                ('state_licensure', models.BooleanField(default=False)),
                ('previous_classwork', models.BooleanField(default=False)),
                ('previous_name', models.CharField(max_length=80)),
                ('educator_role', models.ManyToManyField(related_name='educator_role', to='search_module.EducatorRole')),
                ('institution_affilation', models.ManyToManyField(related_name='institution_affolation', to='search_module.InstituteAffilation')),
            ],
            options={
                'verbose_name_plural': 'Education Details',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super User')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veteran_member', models.BooleanField(default=False)),
                ('veteran_family_member', models.CharField(choices=[('No', 'No'), ('Spouse', 'Spouse'), ('Parent/Guardian', 'Parent/Guardian')], max_length=40)),
                ('educational_benefits', models.BooleanField(default=False)),
                ('formal_disciplinary_action', models.BooleanField(default=False)),
                ('legal_charges', models.BooleanField(default=False)),
                ('pending_criminal_charges', models.BooleanField(default=False)),
                ('restraining_order', models.BooleanField(default=False, verbose_name='Injury to Person/Property')),
            ],
            options={
                'verbose_name_plural': 'Veteran/Legal Details',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('uid', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('campus_of_enrollment', models.CharField(max_length=100)),
                ('student_type', models.CharField(choices=[('Graduate', 'Graduate'), ('Certification', 'Certification')], max_length=13)),
                ('dc_partner', models.CharField(max_length=100)),
                ('currently_enrolled', models.BooleanField(default=False)),
                ('pending_enrollment_request', models.BooleanField(default=False)),
                ('student_name', models.CharField(max_length=40)),
                ('pending_course_request_date', models.DateField()),
                ('course_choice', models.CharField(max_length=50)),
                ('second_course_choice', models.CharField(max_length=50)),
                ('credit_hours_earned', models.PositiveIntegerField()),
                ('campus_affilation', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('citizenship', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=6)),
                ('gender_identity', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('contact_method', models.CharField(choices=[('Text', 'Text'), ('Call', 'Call'), ('Text,Call', 'Text,Call')], max_length=10)),
                ('email', models.EmailField(max_length=40)),
                ('former_name', models.BooleanField(default=False)),
                ('former_name_1', models.CharField(max_length=40)),
                ('former_name_2', models.CharField(max_length=40)),
                ('former_name_3', models.CharField(max_length=40)),
                ('former_name_4', models.CharField(max_length=40)),
                ('former_name_5', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
        migrations.AddField(
            model_name='otherinformation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veteran_details', to='search_module.Student'),
        ),
        migrations.AddField(
            model_name='iueducationdetails',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iu_education_details', to='search_module.Student'),
        ),
        migrations.AddField(
            model_name='instituteaffilation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affilation', to='search_module.Student'),
        ),
        migrations.AddField(
            model_name='educatorrole',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='search_module.Student'),
        ),
        migrations.AddField(
            model_name='address',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_address', to='search_module.Student'),
        ),
    ]
