# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='calculated_remaining',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enroll',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pending_enrollment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_seats',
        ),
    ]
