# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-28 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherinformation',
            name='created_at',
            field=models.DateField(default=True),
        ),
    ]
