# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='funding',
            field=models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='term',
            field=models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], max_length=100),
        ),
    ]
