# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormerName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('former_name', models.BooleanField(default=False)),
                ('former_name_1', models.CharField(max_length=80)),
                ('former_name_2', models.CharField(max_length=80)),
                ('former_name_3', models.CharField(max_length=80)),
                ('former_name_4', models.CharField(max_length=80)),
                ('former_name_5', models.CharField(max_length=80)),
                ('qualtrics_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='former_name', to='search_module.Qualtrics')),
            ],
        ),
        migrations.RemoveField(
            model_name='permanentaddress',
            name='qualtrics_detail',
        ),
        migrations.AlterModelOptions(
            name='grantenrollmentdata',
            options={'verbose_name_plural': 'EnrollmentData'},
        ),
        migrations.AddField(
            model_name='otherinformation',
            name='currently_enroll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherinformation',
            name='previous_classwork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherinformation',
            name='state_Licensure',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PermanentAddress',
        ),
    ]
