# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='term',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three')], max_length=100),
        ),
    ]
