# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0002_auto_20190125_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollmentHistery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('class_student', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=200)),
                ('student_funding', models.CharField(max_length=200)),
                ('student_enrollment', models.CharField(max_length=200)),
                ('student_grade', models.CharField(max_length=100)),
                ('credit_house', models.PositiveIntegerField()),
                ('st_en_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollment_history', to='search_module.Student')),
            ],
            options={
                'verbose_name_plural': 'Student Enrollment Histery',
            },
        ),
    ]
