# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0002_auto_20190130_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search_module.Student', verbose_name='student_comment'),
            preserve_default=False,
        ),
    ]
