# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-07 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0003_auto_20190107_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='former_name_1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='former_name_2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='former_name_3',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='former_name_4',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='former_name_5',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
