# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0003_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pending_enroll',
        ),
    ]
