# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0006_auto_20190116_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_inst_name', models.CharField(max_length=80)),
                ('class_inst_gds_email', models.EmailField(max_length=255)),
                ('grant_en_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_detail', to='search_module.GrantEnrollmentData')),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='pending_enrollment_request',
            new_name='pending_enrollment',
        ),
    ]
