# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0007_auto_20190118_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatorrole',
            name='role',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='instituteaffilation',
            name='institute',
            field=models.CharField(max_length=500),
        ),
    ]
