# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0008_auto_20190121_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educatorrole',
            name='student',
        ),
        migrations.RemoveField(
            model_name='instituteaffilation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='iueducationdetails',
            name='educator_role',
        ),
        migrations.RemoveField(
            model_name='iueducationdetails',
            name='institution_affilation',
        ),
        migrations.DeleteModel(
            name='EducatorRole',
        ),
        migrations.DeleteModel(
            name='InstituteAffilation',
        ),
    ]
