# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0011_auto_20190122_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=80)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
