# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0012_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualtrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('IP Address', 'IP Address'), ('Survey Preview', 'Survey Preview')], default='IP Address', max_length=14)),
                ('ip_address', models.GenericIPAddressField()),
                ('progress', models.PositiveIntegerField()),
                ('response_id', models.CharField(max_length=30, verbose_name='Application ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('recorded_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Qualtrics Data',
            },
        ),
        migrations.CreateModel(
            name='RecipientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_first_name', models.CharField(max_length=40)),
                ('recipient_last_name', models.CharField(max_length=40)),
                ('recipient_email', models.EmailField(max_length=255)),
                ('external_data_reference', models.CharField(max_length=80)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=15)),
                ('distribution_channel', models.CharField(choices=[('anonymous', 'anonymous'), ('preview', 'preview')], max_length=9)),
                ('qualtrics_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_details', to='search_module.Qualtrics')),
            ],
            options={
                'verbose_name_plural': 'Recipient Details',
            },
        ),
    ]
