# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_module', '0014_auto_20190123_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_id', models.CharField(max_length=10)),
                ('campus', models.CharField(max_length=10)),
                ('grant_name', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=10)),
                ('amount_total', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'campus',
            },
        ),
    ]
